# Numpy and Python Functions, Modules

## Table of Contents
1. Numpy Introduction
2. Python Functions
3. Python Modules

## 1. Numpy Introduction

### 1.1 Why Numpy?
Numpy is a powerful library for numerical computing in Python. It provides efficient, easy-to-use data structures like **arrays** and **matrices**, and is optimized for **mathematical operations**. Numpy is widely used in scientific computing, data analysis, and machine learning.


### 1.2 Numpy Arrays vs Python Lists
Numpy arrays are the main data structure provided by the library. They are similar to Python lists but are more efficient and provide additional functionality for mathematical operations. Some differences include:

- Numpy arrays are homogeneous (all elements must be of the same type), while Python lists can be heterogeneous.
- Numpy arrays support element-wise operations, while Python lists do not.
- Numpy arrays are more memory-efficient and faster for numerical computations than Python lists.

### 1.3 Basic Operations
Numpy arrays support basic arithmetic operations, broadcasting, indexing, and slicing.

### 1.4 Examples

In [1]:
import numpy as np

# Creating a numpy array and Python list
a = np.array([1, 2, 3, 4, 5])
lst = [1, 2, 3, 4, 5]

In [2]:
# Element-wise operations with numpy arrays
print(a + 5)
print(a * 2) 

[ 6  7  8  9 10]
[ 2  4  6  8 10]


In [3]:
# Broadcasting with numpy arrays
b = np.array([2, 2, 2, 2, 2])
print(a * b)

[ 2  4  6  8 10]


In [4]:
# Element-wise operations are not supported with Python lists
# The following lines of code would raise an error
print(lst + 5)
print(lst * 2)

TypeError: can only concatenate list (not "int") to list

In [5]:
# Indexing and slicing with numpy arrays
print(a[1])       # Output: 2
print(a[1:4])

2
[2 3 4]


In [6]:
# Indexing and slicing with Python lists
print(lst[1])
print(lst[1:4]) 

2
[2, 3, 4]


In [8]:
a2 = np.array([1, 2, "book", "2"])
a2

array(['1', '2', 'book', '2'], dtype='<U21')

## 2. Python Functions

### 2.1 Overview
Functions are blocks of code that perform a specific task and can be reused throughout a program. They improve code readability and modularity, making it easier to maintain and debug. Functions are defined using the `def` keyword, followed by the function name, a pair of parentheses containing input arguments, and a colon. The function body is indented and usually ends with a `return` statement to provide the output.

### 2.2 Function Syntax

In [9]:
def function_name(arguments):
    # Function body
    result = perform_some_operation(arguments)
    return result

### 2.3 Examples
#### Example 1: Simple Function

In [10]:
def greet(name):
    return f"Hello, {name}!"

print(greet("Alice"))  # Output: "Hello, Alice!"

Hello, Alice!


#### Example 2: Function with Multiple Arguments

In [11]:
def add(a, b):
    return a + b

print(add(3, 5))  # Output: 8

8


#### Example 3: Function with Default Argument Values

In [12]:
def power(base, exponent=2):
    return base ** exponent

In [13]:
print(power(3))

9


In [14]:
print(power(3, 3))

27


### 2.4 Exercises

#### Exercise 1

Write a function that accepts two numbers and returns their product.

#### Exercise 2

Write a function that takes a list of numbers and returns the maximum value.

## 3. Python Modules

### 3.1 Overview
Modules in Python are files containing Python code, which can include variables, functions, and classes. They allow you to organize your code in a logical and reusable manner. By importing modules, you can access their functionality in your own code without having to rewrite the same code.

### 3.2 Importing Modules
To use a module in your code, you first need to import it using the `import` keyword, followed by the module name.

```python
import module_name


After importing a module, you can access its functions, classes, or variables using dot notation.

```python
result = module_name.function_name(arguments)


### 3.3 Examples

#### Example 1: Importing the math module

The math module is a built-in Python module that provides various mathematical functions and constants.

In [17]:
import math

# Calculate the square root of 16
sqrt_result = math.sqrt(16)
print(sqrt_result)

4.0


In [16]:
# Calculate the cosine of 45 degrees
cos_result = math.cos(math.radians(45))
print(cos_result)

0.7071067811865476


#### Example 2: Importing a specific function from a module

Instead of importing the entire module, you can import a specific function using the `from ... import ...` statement.

In [18]:
from math import sqrt

# Calculate the square root of 16
sqrt_result = sqrt(16)
print(sqrt_result)

4.0


#### Example 3: Importing a module with an alias

If you want to use a shorter name for a module, you can import it with an alias using the as keyword.

In [20]:
import math as m

# Calculate the square root of 16
sqrt_result = m.sqrt(16)
print(sqrt_result)

4.0


### 3.4 Exercises

#### Exercise 1

Import the random module and generate a random integer between 1 and 100.

#### Exercise 2

Use the datetime module to find the current date and time, and print it in the format "YYYY-MM-DD HH:MM:SS".